### ISSUE TITLE
Host on a maven repository

### ISSUE THREAD

**Issue by n0ct** [IPECTER/LighterAPI#1]
Hello,
Nice work !
Could you please upload your jar on a maven repository ?
[Here is one of the multiple ways for doing so](https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github/14013645#14013645).
Thank you very much !

**Comment by IPECTER** [comment]
Jitpack i will

**Comment by IPECTER** [comment]
@n0ct 
Just use original LightAPI maven
API is same
